version: '3'

services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"

  machine-learning-client:
    build:
      context: .
      dockerfile: machine-learning-client/Dockerfile
    ports:
      - "5003:5000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017
      - MONGO_DBNAME=object_recognition_db
    depends_on:
      - mongodb
    volumes:
      - ./machine-learning-client:/app

  web-app:
    build:
      context: .
      dockerfile: web-app/Dockerfile
    ports:
      - "8001:5000"
    environment:
      - ML_CLIENT_URL=http://machine-learning-client:5003
      - MONGO_URI=mongodb://mongodb:27017
      - MONGO_DBNAME=object_recognition_db
    depends_on:
      - mongodb
      - machine-learning-client
    volumes:
      - ./web-app:/app
