version: '3'

services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"

  machine-learning-client:
    build:
      context: .
      dockerfile: Dockerfile.mlc
    ports:
      - "5003:5003"
    environment:
      - MONGO_URI=mongodb://mongodb:27017
      - MONGO_DBNAME=expressions
    depends_on:
      - mongodb

  web-app:
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
     - "8001:8001"
    environment:
      - MONGO_URI=mongodb://mongodb:27017
      - MONGO_DBNAME=object_recognition_db
    depends_on:
      - mongodb
