version: '3'

services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"

  machine-learning-client:
    build:
      context: ./machine-learning-client
      dockerfile: dockerfile.mlc
    image: wwxihan/machine-learning-client:latest
    container_name: mlc-container
    ports:
      - "5003:5003"
    environment:
      - MONGO_URI=mongodb://mongodb:27017
      - MONGO_DBNAME=object_recognition_db
    depends_on:
      - mongodb
    volumes:
      - ./machine-learning-client:/app
      - uploads:/app/uploads

  web-app:
    build:
      context: ./web-app
      dockerfile: dockerfile.web
    image: wwxihan/web-app:latest
    container_name: web-app-container
    ports:
      - "8001:8001"
    environment:
      - ML_CLIENT_URL=http://machine-learning-client:5003
      - MONGO_URI=mongodb://mongodb:27017
      - MONGO_DBNAME=object_recognition_db
    depends_on:
      - mongodb
      - machine-learning-client
    volumes:
      - ./web-app:/app
      - uploads:/app/uploads

volumes:
  uploads:
