# Use an official Python runtime as a parent image
FROM python:3.10

# Set the working directory to /app
WORKDIR /web_app

# Copy just the requirements.txt initially
COPY requirements.txt .

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of your application's code
COPY . .


# Expose the port your application runs on
EXPOSE 8001

# Environment variables for MongoDB
ENV MONGO_HOST=mongodb
ENV MONGO_PORT=27017
ENV MONGO_URI=mongodb://mongodb:27017
ENV MONGO_DBNAME=object_recognition_db
ENV ML_CLIENT_URL=http://machine-learning-client:5003
ENV FLASK_APP=app.py
ENV FLASK_RUN_HOST=0.0.0.0

# Command to run your application
CMD ["python", "app.py"]
